import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "./components/footer";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import Provider from "../components/provider";

import { GoogleAnalytics } from "@next/third-parties/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Telc Prüpung B2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* G-Z92WPDCDMK */}

      <body className={inter.className}>
        <Provider>
          <div className="w-full h-[100%] dark:bg-dark bg-[#efefef] dark:bg-[#011220d6]  ">
            {children}
            <Footer />
            <ToastContainer position="bottom-right" />
          </div>
        </Provider>
        <GoogleAnalytics gaId="G-Z92WPDCDMK" />
      </body>
    </html>
  );
}
