import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "./components/footer";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import Provider from "../components/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Telc Prüpung B2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode,
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-[100%] dark:bg-dark bg-[#efefef] dark:bg-[#011220d6]  ">
          <Provider>
            {children}
            <Footer />
            <ToastContainer position="bottom-right" />
          </Provider>
        </div>
      </body>
    </html>
  );
}
